#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Penggunaan: delssh <username>"
    exit 1
fi

USERNAME=$1

# Memeriksa apakah user ada
if ! id "$USERNAME" &>/dev/null; then
    echo "Error: User '$USERNAME' tidak ditemukan!"
    exit 1
fi

# Menghapus user (-f untuk paksa)
userdel -f "$USERNAME"

if [ $? -eq 0 ]; then
    echo "======================================"
    echo "Berhasil menghapus SSH Account"
    echo "Username   : $USERNAME"
    echo "======================================"
else
    echo "Error: Gagal menghapus user '$USERNAME'."
    exit 1
fi
